# Site settings
title: Coders
slogan: "Keep Learning.."
email: zkhan1093@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Coders is a blog maintained and run by Zeeshan Khan, Here you will find posts related to technologies and coding, requests and suggestions are encouraged and are heartily welcome
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zkhan93.github.io" # the base hostname & protocol for your site
twitter_username: zkhan1093
github_username:  zkhan93
facebook_username: zeeshankhan.1001
linkedin_username: zkhan93

# Build settings
markdown: kramdown
