baseURL: https://zkhan.in/
languageCode: en-us
title: Zeeshan Khan
theme: PaperMod
defaultTheme: dark

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

menu:
  main:
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 30

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Zeeshan Khan
  description: "A place for my thoughts"
  keywords: [Blog, Linux, Android, Python, Java, C]
  ShowReadingTime: true
  ShowBreadCrumbs: true
  comments: true
  author: Zeeshan Khan
  image: "/me.jpg"

  homeInfoParams:
    title: Hi there wave
    Content: Can be Info, links, about...

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"

  profileMode:
    enabled: true
    subtitle: "Python | Web "
    imageUrl: "/me.jpg"
    imageTitle: "Zeeshan Khan"
    imageWidth: 120
    imageHeight: 120

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

# for search
# https://fusejs.io/api/options.html
fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"]

disqusShortname: coderzkhan
