baseURL: https://zkhan.in/
languageCode: en-us
title: Zeeshan Khan
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

menu:
  main:
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 40
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 50
    - identifier: search
      name: Search
      url: /search/
      weight: 60

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  author: Zeeshan Khan
  image: "/me.jpg"
  description: "A place for my thoughts"
  keywords: [Blog, Linux, Android, Python, Java, C]
  defaultTheme: dark
  ShowReadingTime: true
  ShowBreadCrumbs: true
  hideFooter: true
  comments: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  homeInfoParams:
    imageUrl: "/me.jpg"
    title: "O_o"
    Content: This is where I dump my work so that I can find it later

  socialIcons:
    - name: twitter
      url: "https://twitter.com/zkhan1093"
    - name: linkedin
      url: "https://linkedin.com/in/zkhan93/"
    - name: github
      url: "https://github.com/zkhan93"

  profileMode:
    enabled: false
    subtitle: "Python | Web "
    imageUrl: "/me.jpg"
    imageTitle: "Zeeshan Khan"
    imageWidth: 120
    imageHeight: 120

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

# for search
# https://fusejs.io/api/options.html
fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"]
